require './lib/net/utils'
require './lib/storage/utils'
require 'net/ping'
require 'io/console'

class P2PServersUtilities
    @@max_key_len = 16

    def add_wizard
        print "Enter server hostname (e.g 45.67.89.67, server.domain.com) >>> "
        hostname = $stdin.gets.tr("\n ", "")

        print "\e[A\e[KEnter server ssh port (provide 22 if you don't know) >>> "
        port = $stdin.gets.tr("\n ", "")

        print "\e[A\e[KEnter user for distant server (e.g user, root) >>> "
        user = $stdin.gets.tr("\n ", "")

        print "\e[A\e[KCopy keys (don't type the password at each connection) (y/n) >>> "
        copy = $stdin.gets.tr("\n ", "")

        print "\e[A\e[KEnter wanted server name, max 16 chars (e.g website-prod) >>> "
        name = $stdin.gets.tr("\n ", "")

        while name.length > @@max_key_len
            print "\e[A\e[KEnter wanted server name, max 16 chars (e.g website-prod) >>> "
            name = $stdin.gets.tr("\n ", "")
        end

        if copy.downcase == "y"
            puts "\e[A\e[KCopying keys, your password will be asked:"
            success = system("ssh-copy-id -p #{port} #{user}@#{hostname}")
            if success == false || success == nil
                puts "\e[31mHost cannot be accessible thru ssh. Please make sure a ssh server is running on #{user}@#{hostname} ❌\e[0m"
                exit(-1)
            else
                puts "Trying to login without password..."
                host = P2PNet::Host.new(user, hostname, port)
                unless host.test
                    puts "\e[A\e[K\e[31mFailed, please make sure you provided the correct values. ❌\e[0m"
                    exit
                end
            end
        else
            puts "\e[A\e[KTo verify if distant host is ready, please enter your password."
            host = P2PNet::Host.new(user, hostname, port, password=true)
            unless host.test
                puts "\e[A\e[K\e[31mFailed, please make sure you provided the correct values. ❌\e[0m"
                exit
            end
        end

        servers = Storage.read("servers")

        servers['data'] << {
          "hostname" => hostname,
          "user" => user,
          "port" => port,
          "require_password" => copy.downcase != "y",
          "name" => name
        }

        Storage.write(servers, "servers")
        puts "\e[A\e[K\e[A\e[K\e[A\e[K\e[A\e[K\e[A\e[K\e[A\e[K\e[32mServer successfully added. ✅\e[0m"
    end

    def list
        return Storage.read("servers")['data']
    end

    def get(name)
        servers = Storage.read("servers")['data']
        servers.each do |server|
            if server['name'] == name
                return server
            end
        end
        return nil
    end

    def remove(name)
        servers = Storage.read("servers")
        servers['data'].each do |server|
            if server['name'] == name
                index = servers['data'].find_index(server)
                servers['data'].delete_at(index)
                Storage.write(servers, "servers")
                return server
            end
        end
        return nil
    end

    def save_to_p2p(name)
        server = P2PServersUtilities.get(name)
        puts "Connecting to #{name}... Type \"close\" to exit and \"abort\" to abort."
        host = P2PNet::Host.new(server['user'], server['hostname'], server['port'], server['require_password'])
        commands = ["DIST #{name}"]
        context = host.call('pwd').tr("\n", "")
        while true
            user = host.call('whoami').tr("\n", "")
            print "\e[32m#{user}@#{server['hostname']}\e[0m:\e[34m#{context} $\e[0m "
            command = $stdin.gets.tr("\n", "")
            if command == 'close'
                break
            elsif command == 'abort'
                puts "\n\e[31mAborted ❌\e[0m"
                puts "\e[2mserver '#{name}' - p2p #{CONFIG["version"]}\e[0m"
            elsif command.start_with?('cd')
                arg = command.gsub('cd ', '')
                if arg.start_with?('/')
                    target = arg
                else
                    unless context.end_with?('/')
                        context += '/'
                    end
                    target = context + arg
                end
                context = target
                commands.push("CTX #{target}")
                puts "\e[2m\t-> Translating \"cd\" to \"CTX\"; moved to #{target}\e[0m"
            else
                commands.push("COMMAND #{command}")
                output = host.call("cd #{context} && #{command}").gsub("\n", "\n\t   ")
                puts "\e[2m\t-> #{output}\e[0m"
            end
        end
        commands.push("# Generated by p2p init\n")
        File.write('.p2p', commands.join("\n"))
        puts "\n\e[32m.p2p file successfully generated ✅\e[0m"
        puts "\e[2mserver '#{name}' - p2p #{CONFIG["version"]}\e[0m"
    end
end
